name       : foobillardplus
version    : 3.42
release    : 2
source     :
    - https://jaist.dl.sourceforge.net/project/foobillardplus/source/foobillardplus-3.42beta.tar.gz : e276b70674a7d788c45eeff89f1f5db5d48d871a1ab92103813d424a3761e1d9
license    : GPL-2.0
component  : games
summary    : Foobillard++ - Pool Game
description: |
    An OpenGL Billard Game based on foobillard 3.0a with patches, new features (hud, jumpshots, correct detection of lost balls, more sound and graphics etc). Optimized for touch. New designed mouse / touch-control.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(glu)
    - pkgconfig(SDL_mixer)
    - pkgconfig(SDL_net)
setup      : |
    %reconfigure --prefix=/usr/share --disable-fastmath
build      : |
    %make
install    : |
    %make_install prefix="$installdir/usr/share" datadir="$installdir/usr/share/foobillardplus/data"

    rm -rf $installdir/usr/share/{AUTHORS,COPYING,ChangeLog,INSTALL,README,TODO,foobillardplus.desktop}
    install -dm00644 $installdir/usr/{bin,share/{applications,pixmaps}}
    install -Dm00644 $pkgfiles/foobillardplus.desktop $installdir/usr/share/applications/foobillardplus.desktop
    ln -s /usr/share/foobillardplus/bin/foobillardplus $installdir/usr/bin/foobillardplus
    mv $installdir/usr/share/foobillardplus.{png,xbm} $installdir/usr/share/pixmaps/
